-- -*- sql-product: postgres -*-

BEGIN;

CREATE SCHEMA ancillary;
GRANT USAGE ON SCHEMA ancillary TO PUBLIC;

CREATE TABLE ancillary.country_codes (
    "name"      TEXT   NOT NULL UNIQUE CHECK ("name" <> ''),
    "cc3"       CITEXT NOT NULL UNIQUE CHECK ("cc3"  <> ''),
    "cc2"       CITEXT NOT NULL UNIQUE CHECK ("cc2"  <> '')
);
GRANT SELECT ON ancillary.country_codes TO PUBLIC;

CREATE SCHEMA geolocation;
GRANT USAGE ON SCHEMA geolocation TO PUBLIC;

CREATE TABLE geolocation.hosts (
       "class"     TEXT    NOT NULL,
       "label"     TEXT    NOT NULL UNIQUE,
       "ipv4"      INET    NOT NULL UNIQUE,
       "asn"       INTEGER NOT NULL,
       "country"   CITEXT  NOT NULL DEFAULT('zz')
                           REFERENCES ancillary.country_codes(cc2),
       "latitude"  REAL    NOT NULL DEFAULT(0),
       "longitude" REAL    NOT NULL DEFAULT(0),
       "annot"     JSONB   NOT NULL DEFAULT('{}')
);
GRANT SELECT ON geolocation.hosts TO PUBLIC;

CREATE TABLE geolocation.batches (
       "id"          SERIAL    NOT NULL PRIMARY KEY,
       "date"        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
       "proxied"     BOOLEAN   NOT NULL DEFAULT(FALSE),
       "client_lat"  REAL      NOT NULL DEFAULT(0),
       "client_lon"  REAL      NOT NULL DEFAULT(0),
       "client_addr" INET      NOT NULL DEFAULT('0.0.0.0'),
       "proxy_lat"   REAL      NOT NULL DEFAULT(0),
       "proxy_lon"   REAL      NOT NULL DEFAULT(0),
       "proxy_addr"  INET      NOT NULL DEFAULT('0.0.0.0'),
       "annot"       JSONB     NOT NULL DEFAULT('{}')
);
GRANT SELECT ON geolocation.batches TO PUBLIC;

CREATE TABLE geolocation.measurements (
       "batch"  INTEGER NOT NULL REFERENCES geolocation.batches(id),
       "src"    INET    NOT NULL REFERENCES geolocation.hosts(ipv4),
       "dst"    INET    NOT NULL,-- REFERENCES geolocation.hosts(ipv4),
       "rtt"    REAL    NOT NULL CHECK ("rtt" >= 0),
       "status" INTEGER NOT NULL
);
CREATE INDEX measurements_src ON geolocation.measurements(src);
CREATE INDEX measurements_dst ON geolocation.measurements(dst);

GRANT SELECT ON geolocation.measurements TO PUBLIC;


-- Data taken from http://www.opengeocode.org/download/countrynames.txt
-- (ISO 3166-1 alpha-2,3 codes and English short names)
-- Names have been systematically simplified.
INSERT INTO ancillary.country_codes (cc2, cc3, name) VALUES
('af', 'afg', 'Afghanistan'),
('ax', 'ala', 'Aland Islands'),
('al', 'alb', 'Albania'),
('dz', 'dza', 'Algeria'),
('as', 'asm', 'American Samoa'),
('ad', 'and', 'Andorra'),
('ao', 'ago', 'Angola'),
('ai', 'aia', 'Anguilla'),
('aq', 'ata', 'Antarctica'),
('ag', 'atg', 'Antigua and Barbuda'),
('ar', 'arg', 'Argentina'),
('am', 'arm', 'Armenia'),
('aw', 'abw', 'Aruba'),
('au', 'aus', 'Australia'),
('at', 'aut', 'Austria'),
('az', 'aze', 'Azerbaijan'),
('bs', 'bhs', 'Bahamas'),
('bh', 'bhr', 'Bahrain'),
('bd', 'bgd', 'Bangladesh'),
('bb', 'brb', 'Barbados'),
('by', 'blr', 'Belarus'),
('be', 'bel', 'Belgium'),
('bz', 'blz', 'Belize'),
('bj', 'ben', 'Benin'),
('bm', 'bmu', 'Bermuda'),
('bt', 'btn', 'Bhutan'),
('bo', 'bol', 'Bolivia'),
('bq', 'bes', 'Bonaire, Saint Eustatius and Saba'),
('ba', 'bih', 'Bosnia and Herzegovina'),
('bw', 'bwa', 'Botswana'),
('bv', 'bvt', 'Bouvet Island'),
('br', 'bra', 'Brazil'),
('io', 'iot', 'British Indian Ocean Territory'),
('bn', 'brn', 'Brunei'),
('bg', 'bgr', 'Bulgaria'),
('bf', 'bfa', 'Burkina Faso'),
('bi', 'bdi', 'Burundi'),
('kh', 'khm', 'Cambodia'),
('cm', 'cmr', 'Cameroon'),
('ca', 'can', 'Canada'),
('cv', 'cpv', 'Cape Verde'),
('ky', 'cym', 'Cayman Islands'),
('cf', 'caf', 'Central African Republic'),
('td', 'tcd', 'Chad'),
('cl', 'chl', 'Chile'),
('cn', 'chn', 'China'),
('cx', 'cxr', 'Christmas Island'),
('cc', 'cck', 'Cocos (Keeling) Islands'),
('co', 'col', 'Colombia'),
('km', 'com', 'Comoros'),
('cg', 'cog', 'Congo'),
('cd', 'cod', 'Congo DR'),
('ck', 'cok', 'Cook Islands'),
('cr', 'cri', 'Costa Rica'),
('ci', 'civ', 'Cote d’Ivoire'),
('hr', 'hrv', 'Croatia'),
('cu', 'cub', 'Cuba'),
('cw', 'cuw', 'Curacao'),
('cy', 'cyp', 'Cyprus'),
('cz', 'cze', 'Czech Republic'),
('dk', 'dnk', 'Denmark'),
('dj', 'dji', 'Djibouti'),
('dm', 'dma', 'Dominica'),
('do', 'dom', 'Dominican Republic'),
('ec', 'ecu', 'Ecuador'),
('eg', 'egy', 'Egypt'),
('sv', 'slv', 'El Salvador'),
('gq', 'gnq', 'Equatorial Guinea'),
('er', 'eri', 'Eritrea'),
('ee', 'est', 'Estonia'),
('et', 'eth', 'Ethiopia'),
('fk', 'flk', 'Falkland Islands'),
('fo', 'fro', 'Faroe Islands'),
('fj', 'fji', 'Fiji'),
('fi', 'fin', 'Finland'),
('fr', 'fra', 'France'),
('gf', 'guf', 'French Guiana'),
('pf', 'pyf', 'French Polynesia'),
('tf', 'atf', 'French Southern Territories'),
('ga', 'gab', 'Gabon'),
('gm', 'gmb', 'Gambia'),
('ge', 'geo', 'Georgia'),
('de', 'deu', 'Germany'),
('gh', 'gha', 'Ghana'),
('gi', 'gib', 'Gibraltar'),
('gr', 'grc', 'Greece'),
('gl', 'grl', 'Greenland'),
('gd', 'grd', 'Grenada'),
('gp', 'glp', 'Guadeloupe'),
('gu', 'gum', 'Guam'),
('gt', 'gtm', 'Guatemala'),
('gg', 'ggy', 'Guernsey'),
('gn', 'gin', 'Guinea'),
('gw', 'gnb', 'Guinea-Bissau'),
('gy', 'guy', 'Guyana'),
('ht', 'hti', 'Haiti'),
('hm', 'hmd', 'Heard Island and McDonald Islands'),
('va', 'vat', 'Vatican'),
('hn', 'hnd', 'Honduras'),
('hk', 'hkg', 'Hong Kong'),
('hu', 'hun', 'Hungary'),
('is', 'isl', 'Iceland'),
('in', 'ind', 'India'),
('id', 'idn', 'Indonesia'),
('ir', 'irn', 'Iran'),
('iq', 'irq', 'Iraq'),
('ie', 'irl', 'Ireland'),
('im', 'imn', 'Isle of Man'),
('il', 'isr', 'Israel'),
('it', 'ita', 'Italy'),
('jm', 'jam', 'Jamaica'),
('jp', 'jpn', 'Japan'),
('je', 'jey', 'Jersey'),
('jo', 'jor', 'Jordan'),
('kz', 'kaz', 'Kazakhstan'),
('ke', 'ken', 'Kenya'),
('ki', 'kir', 'Kiribati'),
('kp', 'prk', 'North Korea'),
('kr', 'kor', 'South Korea'),
('kw', 'kwt', 'Kuwait'),
('kg', 'kgz', 'Kyrgyzstan'),
('la', 'lao', 'Lao'),
('lv', 'lva', 'Latvia'),
('lb', 'lbn', 'Lebanon'),
('ls', 'lso', 'Lesotho'),
('lr', 'lbr', 'Liberia'),
('ly', 'lby', 'Libya'),
('li', 'lie', 'Liechtenstein'),
('lt', 'ltu', 'Lithuania'),
('lu', 'lux', 'Luxembourg'),
('mo', 'mac', 'Macao'),
('mk', 'mkd', 'Macedonia'),
('mg', 'mdg', 'Madagascar'),
('mw', 'mwi', 'Malawi'),
('my', 'mys', 'Malaysia'),
('mv', 'mdv', 'Maldives'),
('ml', 'mli', 'Mali'),
('mt', 'mlt', 'Malta'),
('mh', 'mhl', 'Marshall Islands'),
('mq', 'mtq', 'Martinique'),
('mr', 'mrt', 'Mauritania'),
('mu', 'mus', 'Mauritius'),
('yt', 'myt', 'Mayotte'),
('mx', 'mex', 'Mexico'),
('fm', 'fsm', 'Micronesia'),
('md', 'mda', 'Moldova'),
('mc', 'mco', 'Monaco'),
('mn', 'mng', 'Mongolia'),
('me', 'mne', 'Montenegro'),
('ms', 'msr', 'Montserrat'),
('ma', 'mar', 'Morocco'),
('mz', 'moz', 'Mozambique'),
('mm', 'mmr', 'Myanmar'),
('na', 'nam', 'Namibia'),
('nr', 'nru', 'Nauru'),
('np', 'npl', 'Nepal'),
('nl', 'nld', 'Netherlands'),
('nc', 'ncl', 'New Caledonia'),
('nz', 'nzl', 'New Zealand'),
('ni', 'nic', 'Nicaragua'),
('ne', 'ner', 'Niger'),
('ng', 'nga', 'Nigeria'),
('nu', 'niu', 'Niue'),
('nf', 'nfk', 'Norfolk Island'),
('mp', 'mnp', 'Northern Mariana Islands'),
('no', 'nor', 'Norway'),
('ps', 'pse', 'Palestine'),
('om', 'omn', 'Oman'),
('pk', 'pak', 'Pakistan'),
('pw', 'plw', 'Palau'),
('pa', 'pan', 'Panama'),
('pg', 'png', 'Papua New Guinea'),
('py', 'pry', 'Paraguay'),
('pe', 'per', 'Peru'),
('ph', 'phl', 'Philippines'),
('pn', 'pcn', 'Pitcairn'),
('pl', 'pol', 'Poland'),
('pt', 'prt', 'Portugal'),
('pr', 'pri', 'Puerto Rico'),
('qa', 'qat', 'Qatar'),
('re', 'reu', 'Reunion'),
('ro', 'rou', 'Romania'),
('ru', 'rus', 'Russia'),
('rw', 'rwa', 'Rwanda'),
('bl', 'blm', 'Saint Barthelemy'),
('sh', 'shn', 'Saint Helena, Ascension and Tristan da Cunha'),
('kn', 'kna', 'Saint Kitts and Nevis'),
('lc', 'lca', 'Saint Lucia'),
('mf', 'maf', 'Saint Martin (French part)'),
('pm', 'spm', 'Saint Pierre and Miquelon'),
('vc', 'vct', 'Saint Vincent and The Grenadines'),
('ws', 'wsm', 'Samoa'),
('sm', 'smr', 'San Marino'),
('st', 'stp', 'Sao Tome and Principe'),
('sa', 'sau', 'Saudi Arabia'),
('sn', 'sen', 'Senegal'),
('rs', 'srb', 'Serbia'),
('sc', 'syc', 'Seychelles'),
('sl', 'sle', 'Sierra Leone'),
('sg', 'sgp', 'Singapore'),
('sx', 'sxm', 'Sint Maarten (Dutch part)'),
('sk', 'svk', 'Slovakia'),
('si', 'svn', 'Slovenia'),
('sb', 'slb', 'Solomon Islands'),
('so', 'som', 'Somalia'),
('za', 'zaf', 'South Africa'),
('gs', 'sgs', 'South Georgia and the South Sandwich Islands'),
('es', 'esp', 'Spain'),
('lk', 'lka', 'Sri Lanka'),
('sd', 'sdn', 'Sudan'),
('ss', 'ssd', 'South Sudan'),
('sr', 'sur', 'Suriname'),
('sj', 'sjm', 'Svalbard and Jan Mayen'),
('sz', 'swz', 'Swaziland'),
('se', 'swe', 'Sweden'),
('ch', 'che', 'Switzerland'),
('sy', 'syr', 'Syria'),
('tw', 'twn', 'Taiwan'),
('tj', 'tjk', 'Tajikistan'),
('tz', 'tza', 'Tanzania'),
('th', 'tha', 'Thailand'),
('tl', 'tls', 'Timor-Leste'),
('tg', 'tgo', 'Togo'),
('tk', 'tkl', 'Tokelau'),
('to', 'ton', 'Tonga'),
('tt', 'tto', 'Trinidad and Tobago'),
('tn', 'tun', 'Tunisia'),
('tr', 'tur', 'Turkey'),
('tm', 'tkm', 'Turkmenistan'),
('tc', 'tca', 'Turks and Caicos Islands'),
('tv', 'tuv', 'Tuvalu'),
('ug', 'uga', 'Uganda'),
('ua', 'ukr', 'Ukraine'),
('ae', 'are', 'United Arab Emirates'),
('gb', 'gbr', 'United Kingdom'),
('us', 'usa', 'United States'),
('um', 'umi', 'United States Minor Outlying Islands'),
('uy', 'ury', 'Uruguay'),
('uz', 'uzb', 'Uzbekistan'),
('vu', 'vut', 'Vanuatu'),
('ve', 'ven', 'Venezuela'),
('vn', 'vnm', 'Vietnam'),
('vg', 'vgb', 'British Virgin Islands'),
('vi', 'vir', 'U.S. Virgin Islands'),
('wf', 'wlf', 'Wallis and Futuna'),
('eh', 'esh', 'Western Sahara'),
('ye', 'yem', 'Yemen'),
('zm', 'zmb', 'Zambia'),
('zw', 'zwe', 'Zimbabwe'),
-- Regions not officially recognized as countries, that appear in the dataset,
-- are given X-codes from the user-assigned namespace.
('xk', 'xks', 'Kosovo'),
('xn', 'xnc', 'Northern Cyprus'),
-- 'eu' is an exceptionally reserved ISO 3166-1a2 code meaning European Union.
-- There is no corresponding 3166-1a3 code so we use 'xeu' which is in the
-- user-assigned namespace.
('eu', 'xeu', 'European Union'),
-- We use user-assigned codes 'aa[a]' and 'zz[z]' for special purposes.
('aa', 'aaa', 'Anonymous Proxy'),
('zz', 'zzz', 'Unknown');

COMMIT;
