-- -*- sql-product: postgres -*-

BEGIN;

CREATE SCHEMA ancillary;
GRANT USAGE ON SCHEMA ancillary TO PUBLIC;

CREATE TABLE ancillary.country_codes (
    "name"      TEXT   NOT NULL UNIQUE CHECK ("name" <> ''),
    "cc3"       CITEXT NOT NULL UNIQUE CHECK ("cc3"  <> ''),
    "cc2"       CITEXT NOT NULL UNIQUE CHECK ("cc2"  <> ''),
    "region"    TEXT   NOT NULL        CHECK ("region" <> '')
);
GRANT SELECT ON ancillary.country_codes TO PUBLIC;

CREATE SCHEMA geolocation;
GRANT USAGE ON SCHEMA geolocation TO PUBLIC;

CREATE TABLE geolocation.hosts (
       "class"     TEXT    NOT NULL,
       "label"     TEXT    NOT NULL UNIQUE,
       "ipv4"      INET    NOT NULL UNIQUE,
       "asn"       INTEGER NOT NULL,
       "country"   CITEXT  NOT NULL DEFAULT('zz')
                           REFERENCES ancillary.country_codes(cc2),
       "latitude"  REAL    NOT NULL DEFAULT(0),
       "longitude" REAL    NOT NULL DEFAULT(0),
       "annot"     JSONB   NOT NULL DEFAULT('{}')
);
GRANT SELECT ON geolocation.hosts TO PUBLIC;

CREATE TABLE geolocation.batches (
       "id"          SERIAL    NOT NULL PRIMARY KEY,
       "date"        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
       "proxied"     BOOLEAN   NOT NULL DEFAULT(FALSE),
       "client_lat"  REAL      NOT NULL DEFAULT(0),
       "client_lon"  REAL      NOT NULL DEFAULT(0),
       "client_addr" INET      NOT NULL DEFAULT('0.0.0.0'),
       "proxy_lat"   REAL      NOT NULL DEFAULT(0),
       "proxy_lon"   REAL      NOT NULL DEFAULT(0),
       "proxy_addr"  INET      NOT NULL DEFAULT('0.0.0.0'),
       "annot"       JSONB     NOT NULL DEFAULT('{}')
);
GRANT SELECT ON geolocation.batches TO PUBLIC;

CREATE TABLE geolocation.measurements (
       "batch"  INTEGER NOT NULL REFERENCES geolocation.batches(id),
       "src"    INET    NOT NULL REFERENCES geolocation.hosts(ipv4),
       "dst"    INET    NOT NULL,-- REFERENCES geolocation.hosts(ipv4),
       "rtt"    REAL    NOT NULL CHECK ("rtt" >= 0),
       "status" INTEGER NOT NULL
);
CREATE INDEX measurements_src ON geolocation.measurements(src);
CREATE INDEX measurements_dst ON geolocation.measurements(dst);

GRANT SELECT ON geolocation.measurements TO PUBLIC;


-- Country data taken from http://www.opengeocode.org/download/countrynames.txt
-- (ISO 3166-1 alpha-2,3 codes and English short names)
-- Names have been systematically simplified.
-- Region data from Natural Earth:
-- http://www.naturalearthdata.com/downloads/50m-cultural-vectors/
-- with some changes.

INSERT INTO ancillary.country_codes ("cc2", "cc3", "region", "name") VALUES
('abw', 'aw', 'Caribbean',                 'Aruba'),
('afg', 'af', 'South Asia',                'Afghanistan'),
('ago', 'ao', 'Middle Africa',             'Angola'),
('aia', 'ai', 'Caribbean',                 'Anguilla'),
('ala', 'ax', 'North Europe',              'Aland Islands'),
('alb', 'al', 'South Europe',              'Albania'),
('and', 'ad', 'South Europe',              'Andorra'),
('are', 'ae', 'Middle East',               'United Arab Emirates'),
('arg', 'ar', 'South America',             'Argentina'),
('arm', 'am', 'Middle East',               'Armenia'),
('asm', 'as', 'Oceania',                   'American Samoa'),
('ata', 'aq', 'Antarctica',                'Antarctica'),
('atf', 'tf', 'Oceania',                   'French Southern Territories'),
('atg', 'ag', 'Caribbean',                 'Antigua and Barbuda'),
('aus', 'au', 'Australia and New Zealand', 'Australia'),
('aut', 'at', 'West Europe',               'Austria'),
('aze', 'az', 'Middle East',               'Azerbaijan'),
('bdi', 'bi', 'East Africa',               'Burundi'),
('bel', 'be', 'West Europe',               'Belgium'),
('ben', 'bj', 'West Africa',               'Benin'),
('bes', 'bq', 'Caribbean',                 'Bonaire, Saint Eustatius and Saba'),
('bfa', 'bf', 'West Africa',               'Burkina Faso'),
('bgd', 'bd', 'South Asia',                'Bangladesh'),
('bgr', 'bg', 'East Europe',               'Bulgaria'),
('bhr', 'bh', 'Middle East',               'Bahrain'),
('bhs', 'bs', 'Caribbean',                 'Bahamas'),
('bih', 'ba', 'South Europe',              'Bosnia and Herzegovina'),
('blm', 'bl', 'Caribbean',                 'Saint Barthelemy'),
('blr', 'by', 'East Europe',               'Belarus'),
('blz', 'bz', 'Central America',           'Belize'),
('bmu', 'bm', 'North America',             'Bermuda'),
('bol', 'bo', 'South America',             'Bolivia'),
('bra', 'br', 'South America',             'Brazil'),
('brb', 'bb', 'Caribbean',                 'Barbados'),
('brn', 'bn', 'Southeast Asia',            'Brunei'),
('btn', 'bt', 'South Asia',                'Bhutan'),
('bvt', 'bv', 'Oceania',                   'Bouvet Island'),
('bwa', 'bw', 'South Africa',              'Botswana'),
('caf', 'cf', 'Middle Africa',             'Central African Republic'),
('can', 'ca', 'North America',             'Canada'),
('cck', 'cc', 'Southeast Asia',            'Cocos (Keeling) Islands'),
('che', 'ch', 'West Europe',               'Switzerland'),
('chl', 'cl', 'South America',             'Chile'),
('chn', 'cn', 'East Asia',                 'China'),
('civ', 'ci', 'West Africa',               'Cote d’Ivoire'),
('cmr', 'cm', 'Middle Africa',             'Cameroon'),
('cod', 'cd', 'Middle Africa',             'Congo DR'),
('cog', 'cg', 'Middle Africa',             'Congo'),
('cok', 'ck', 'Oceania',                   'Cook Islands'),
('col', 'co', 'South America',             'Colombia'),
('com', 'km', 'East Africa',               'Comoros'),
('cpv', 'cv', 'West Africa',               'Cape Verde'),
('cri', 'cr', 'Central America',           'Costa Rica'),
('cub', 'cu', 'Caribbean',                 'Cuba'),
('cuw', 'cw', 'Caribbean',                 'Curacao'),
('cxr', 'cx', 'Southeast Asia',            'Christmas Island'),
('cym', 'ky', 'Caribbean',                 'Cayman Islands'),
('cyp', 'cy', 'Middle East',               'Cyprus'),
('cze', 'cz', 'East Europe',               'Czech Republic'),
('deu', 'de', 'West Europe',               'Germany'),
('dji', 'dj', 'East Africa',               'Djibouti'),
('dma', 'dm', 'Caribbean',                 'Dominica'),
('dnk', 'dk', 'North Europe',              'Denmark'),
('dom', 'do', 'Caribbean',                 'Dominican Republic'),
('dza', 'dz', 'North Africa',              'Algeria'),
('ecu', 'ec', 'South America',             'Ecuador'),
('egy', 'eg', 'North Africa',              'Egypt'),
('eri', 'er', 'East Africa',               'Eritrea'),
('esh', 'eh', 'North Africa',              'Western Sahara'),
('esp', 'es', 'South Europe',              'Spain'),
('est', 'ee', 'North Europe',              'Estonia'),
('eth', 'et', 'East Africa',               'Ethiopia'),
('fin', 'fi', 'North Europe',              'Finland'),
('fji', 'fj', 'Oceania',                   'Fiji'),
('flk', 'fk', 'South America',             'Falkland Islands'),
('fra', 'fr', 'West Europe',               'France'),
('fro', 'fo', 'North Europe',              'Faroe Islands'),
('fsm', 'fm', 'Oceania',                   'Micronesia'),
('gab', 'ga', 'Middle Africa',             'Gabon'),
('gbr', 'gb', 'North Europe',              'United Kingdom'),
('geo', 'ge', 'Middle East',               'Georgia'),
('ggy', 'gg', 'North Europe',              'Guernsey'),
('gha', 'gh', 'West Africa',               'Ghana'),
('gib', 'gi', 'South Europe',              'Gibraltar'),
('gin', 'gn', 'West Africa',               'Guinea'),
('glp', 'gp', 'Caribbean',                 'Guadeloupe'),
('gmb', 'gm', 'West Africa',               'Gambia'),
('gnb', 'gw', 'West Africa',               'Guinea-Bissau'),
('gnq', 'gq', 'Middle Africa',             'Equatorial Guinea'),
('grc', 'gr', 'South Europe',              'Greece'),
('grd', 'gd', 'Caribbean',                 'Grenada'),
('grl', 'gl', 'North America',             'Greenland'),
('gtm', 'gt', 'Central America',           'Guatemala'),
('guf', 'gf', 'South America',             'French Guiana'),
('gum', 'gu', 'Oceania',                   'Guam'),
('guy', 'gy', 'South America',             'Guyana'),
('hkg', 'hk', 'East Asia',                 'Hong Kong'),
('hmd', 'hm', 'Oceania',                   'Heard Island and McDonald Islands'),
('hnd', 'hn', 'Central America',           'Honduras'),
('hrv', 'hr', 'South Europe',              'Croatia'),
('hti', 'ht', 'Caribbean',                 'Haiti'),
('hun', 'hu', 'East Europe',               'Hungary'),
('idn', 'id', 'Southeast Asia',            'Indonesia'),
('imn', 'im', 'North Europe',              'Isle of Man'),
('ind', 'in', 'South Asia',                'India'),
('iot', 'io', 'Oceania',                   'British Indian Ocean Territory'),
('irl', 'ie', 'North Europe',              'Ireland'),
('irn', 'ir', 'South Asia',                'Iran'),
('irq', 'iq', 'Middle East',               'Iraq'),
('isl', 'is', 'North Europe',              'Iceland'),
('isr', 'il', 'Middle East',               'Israel'),
('ita', 'it', 'South Europe',              'Italy'),
('jam', 'jm', 'Caribbean',                 'Jamaica'),
('jey', 'je', 'North Europe',              'Jersey'),
('jor', 'jo', 'Middle East',               'Jordan'),
('jpn', 'jp', 'East Asia',                 'Japan'),
('kaz', 'kz', 'Central Asia',              'Kazakhstan'),
('ken', 'ke', 'East Africa',               'Kenya'),
('kgz', 'kg', 'Central Asia',              'Kyrgyzstan'),
('khm', 'kh', 'Southeast Asia',            'Cambodia'),
('kir', 'ki', 'Oceania',                   'Kiribati'),
('kna', 'kn', 'Caribbean',                 'Saint Kitts and Nevis'),
('kor', 'kr', 'East Asia',                 'South Korea'),
('kwt', 'kw', 'Middle East',               'Kuwait'),
('lao', 'la', 'Southeast Asia',            'Lao'),
('lbn', 'lb', 'Middle East',               'Lebanon'),
('lbr', 'lr', 'West Africa',               'Liberia'),
('lby', 'ly', 'North Africa',              'Libya'),
('lca', 'lc', 'Caribbean',                 'Saint Lucia'),
('lie', 'li', 'West Europe',               'Liechtenstein'),
('lka', 'lk', 'South Asia',                'Sri Lanka'),
('lso', 'ls', 'South Africa',              'Lesotho'),
('ltu', 'lt', 'North Europe',              'Lithuania'),
('lux', 'lu', 'West Europe',               'Luxembourg'),
('lva', 'lv', 'North Europe',              'Latvia'),
('mac', 'mo', 'East Asia',                 'Macao'),
('maf', 'mf', 'Caribbean',                 'Saint Martin (French part)'),
('mar', 'ma', 'North Africa',              'Morocco'),
('mco', 'mc', 'West Europe',               'Monaco'),
('mda', 'md', 'East Europe',               'Moldova'),
('mdg', 'mg', 'East Africa',               'Madagascar'),
('mdv', 'mv', 'South Asia',                'Maldives'),
('mex', 'mx', 'Central America',           'Mexico'),
('mhl', 'mh', 'Oceania',                   'Marshall Islands'),
('mkd', 'mk', 'South Europe',              'Macedonia'),
('mli', 'ml', 'West Africa',               'Mali'),
('mlt', 'mt', 'South Europe',              'Malta'),
('mmr', 'mm', 'Southeast Asia',            'Myanmar'),
('mne', 'me', 'South Europe',              'Montenegro'),
('mng', 'mn', 'East Asia',                 'Mongolia'),
('mnp', 'mp', 'Oceania',                   'Northern Mariana Islands'),
('moz', 'mz', 'East Africa',               'Mozambique'),
('mrt', 'mr', 'West Africa',               'Mauritania'),
('msr', 'ms', 'Caribbean',                 'Montserrat'),
('mtq', 'mq', 'Caribbean',                 'Martinique'),
('mus', 'mu', 'East Africa',               'Mauritius'),
('mwi', 'mw', 'East Africa',               'Malawi'),
('mys', 'my', 'Southeast Asia',            'Malaysia'),
('myt', 'yt', 'East Africa',               'Mayotte'),
('nam', 'na', 'South Africa',              'Namibia'),
('ncl', 'nc', 'Oceania',                   'New Caledonia'),
('ner', 'ne', 'West Africa',               'Niger'),
('nfk', 'nf', 'Australia and New Zealand', 'Norfolk Island'),
('nga', 'ng', 'West Africa',               'Nigeria'),
('nic', 'ni', 'Central America',           'Nicaragua'),
('niu', 'nu', 'Oceania',                   'Niue'),
('nld', 'nl', 'West Europe',               'Netherlands'),
('nor', 'no', 'North Europe',              'Norway'),
('npl', 'np', 'South Asia',                'Nepal'),
('nru', 'nr', 'Oceania',                   'Nauru'),
('nzl', 'nz', 'Australia and New Zealand', 'New Zealand'),
('omn', 'om', 'Middle East',               'Oman'),
('pak', 'pk', 'South Asia',                'Pakistan'),
('pan', 'pa', 'Central America',           'Panama'),
('pcn', 'pn', 'Oceania',                   'Pitcairn'),
('per', 'pe', 'South America',             'Peru'),
('phl', 'ph', 'Southeast Asia',            'Philippines'),
('plw', 'pw', 'Oceania',                   'Palau'),
('png', 'pg', 'Oceania',                   'Papua New Guinea'),
('pol', 'pl', 'East Europe',               'Poland'),
('pri', 'pr', 'Caribbean',                 'Puerto Rico'),
('prk', 'kp', 'East Asia',                 'North Korea'),
('prt', 'pt', 'South Europe',              'Portugal'),
('pry', 'py', 'South America',             'Paraguay'),
('pse', 'ps', 'Middle East',               'Palestine'),
('pyf', 'pf', 'Oceania',                   'French Polynesia'),
('qat', 'qa', 'Middle East',               'Qatar'),
('reu', 're', 'East Africa',               'Reunion'),
('rou', 'ro', 'East Europe',               'Romania'),
('rus', 'ru', 'East Europe',               'Russia'),
('rwa', 'rw', 'East Africa',               'Rwanda'),
('sau', 'sa', 'Middle East',               'Saudi Arabia'),
('sdn', 'sd', 'North Africa',              'Sudan'),
('sen', 'sn', 'West Africa',               'Senegal'),
('sgp', 'sg', 'Southeast Asia',            'Singapore'),
('sgs', 'gs', 'Oceania',                   'South Georgia and the South Sandwich Islands'),
('shn', 'sh', 'West Africa',               'Saint Helena, Ascension and Tristan da Cunha'),
('sjm', 'sj', 'North Europe',              'Svalbard and Jan Mayen'),
('slb', 'sb', 'Oceania',                   'Solomon Islands'),
('sle', 'sl', 'West Africa',               'Sierra Leone'),
('slv', 'sv', 'Central America',           'El Salvador'),
('smr', 'sm', 'South Europe',              'San Marino'),
('som', 'so', 'East Africa',               'Somalia'),
('spm', 'pm', 'North America',             'Saint Pierre and Miquelon'),
('srb', 'rs', 'South Europe',              'Serbia'),
('ssd', 'ss', 'East Africa',               'South Sudan'),
('stp', 'st', 'Middle Africa',             'Sao Tome and Principe'),
('sur', 'sr', 'South America',             'Suriname'),
('svk', 'sk', 'East Europe',               'Slovakia'),
('svn', 'si', 'South Europe',              'Slovenia'),
('swe', 'se', 'North Europe',              'Sweden'),
('swz', 'sz', 'South Africa',              'Swaziland'),
('sxm', 'sx', 'Caribbean',                 'Sint Maarten (Dutch part)'),
('syc', 'sc', 'East Africa',               'Seychelles'),
('syr', 'sy', 'Middle East',               'Syria'),
('tca', 'tc', 'Caribbean',                 'Turks and Caicos Islands'),
('tcd', 'td', 'Middle Africa',             'Chad'),
('tgo', 'tg', 'West Africa',               'Togo'),
('tha', 'th', 'Southeast Asia',            'Thailand'),
('tjk', 'tj', 'Central Asia',              'Tajikistan'),
('tkl', 'tk', 'Oceania',                   'Tokelau'),
('tkm', 'tm', 'Central Asia',              'Turkmenistan'),
('tls', 'tl', 'Southeast Asia',            'Timor-Leste'),
('ton', 'to', 'Oceania',                   'Tonga'),
('tto', 'tt', 'Caribbean',                 'Trinidad and Tobago'),
('tun', 'tn', 'North Africa',              'Tunisia'),
('tur', 'tr', 'Middle East',               'Turkey'),
('tuv', 'tv', 'Oceania',                   'Tuvalu'),
('twn', 'tw', 'East Asia',                 'Taiwan'),
('tza', 'tz', 'East Africa',               'Tanzania'),
('uga', 'ug', 'East Africa',               'Uganda'),
('ukr', 'ua', 'East Europe',               'Ukraine'),
('umi', 'um', 'Oceania',                   'United States Minor Outlying Islands'),
('ury', 'uy', 'South America',             'Uruguay'),
('usa', 'us', 'North America',             'United States'),
('uzb', 'uz', 'Central Asia',              'Uzbekistan'),
('vat', 'va', 'South Europe',              'Vatican'),
('vct', 'vc', 'Caribbean',                 'Saint Vincent and The Grenadines'),
('ven', 've', 'South America',             'Venezuela'),
('vgb', 'vg', 'Caribbean',                 'British Virgin Islands'),
('vir', 'vi', 'Caribbean',                 'U.S. Virgin Islands'),
('vnm', 'vn', 'Southeast Asia',            'Vietnam'),
('vut', 'vu', 'Oceania',                   'Vanuatu'),
('wlf', 'wf', 'Oceania',                   'Wallis and Futuna'),
('wsm', 'ws', 'Oceania',                   'Samoa'),
('yem', 'ye', 'Middle East',               'Yemen'),
('zaf', 'za', 'South Africa',              'South Africa'),
('zmb', 'zm', 'East Africa',               'Zambia'),
('zwe', 'zw', 'East Africa',               'Zimbabwe'),

-- Regions not officially recognized as countries, that appear in the dataset,
-- are given X-codes from the user-assigned namespace.
('xks', 'xk', 'South Europe',              'Kosovo'),
('xnc', 'xn', 'Middle East',               'Northern Cyprus'),
('xsl', 'xs', 'East Africa',               'Somaliland'),

-- 'eu' is an exceptionally reserved ISO 3166-1a2 code meaning European Union.
-- There is no corresponding 3166-1a3 code so we use 'xeu' which is in the
-- user-assigned namespace.  This is the only code given the 'Europe' region.
('xeu', 'eu', 'Europe',  'European Union'),

-- We use user-assigned codes 'aa[a]' and 'zz[z]' for special purposes.
('aaa', 'aa', 'Unknown',                   'Anonymous Proxy'),
('zzz', 'zz', 'Unknown',                   'Unknown');

COMMIT;
